---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    environment: prod
    app: jenkins
spec: 
  minReadySeconds: 5
  replicas: 8
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template: 
    metadata:
      name: jenkins
      labels: 
        environment: prod
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk11
          ports:
            - containerPort: 8080
              protocol: TCP          