---
apiVersion: v1 
kind: Namespace 
metadata: 
  name: roboshop
  labels:
    name: roboshop

---
apiVersion: rbac.authorization.k8s.io
kind: Role
metadata: 
  name: roboshop
  namespace: roboshop-admin-Role
rules:
  - apiGroups: ["*"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]    

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: roboshop-admin-RoleBinding
  namespace: roboshop
roleRef:
  name: roboshop-admin-role
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: roboshop-admin-Role
    kind: User
    apiGroup: rbac.authorization.k8s.io  
