---
apiVersion: v1
kind: Service
metadata:
  name: expose-svc
spec:
  selector:
    purpose: nodeselector
  type: LoadBalancer
  ports:
    - name: nginx-svc
      port: 80
      targetPort: 8080
      protocol: TCP